### ISSUE TITLE
NoResourceAvailableException - Flink job in a Docker on K8s 

### ISSUE THREAD

**Issue by akshatashan** [Aleksandr-Filichkin/flink-k8s#1]
Thanks for the detailed explanation. 
I am trying to run the docker in a flink cluster within kubernetes. I have minikube installed for a local setup. 

I pulled the docker image `afilichkin/flink-k8s-with-submit-job` on my local machine and pointed to this image in the jobmanager-deployment.yaml.

After creating the set up, I open up the flink ui using the minikube command
`minikube service flink-jobmanager`

I see the jar file running in the flink ui but the number of TaskManagers is 0.Hence the job fails with the error 
<img width="1429" alt="screenshot 2018-12-04 at 22 11 36" src="https://user-images.githubusercontent.com/675315/49473688-06fb4e00-f813-11e8-8c49-1411cb537c7a.png">

The logs show the following error after the job fails.
`org.apache.flink.runtime.jobmanager.scheduler.NoResourceAvailableException: Could not allocate all requires slots within timeout of 300000 ms.`

The Jobmanager configuration shows
<img width="1008" alt="screenshot 2018-12-04 at 22 23 28" src="https://user-images.githubusercontent.com/675315/49473852-7113f300-f813-11e8-839c-9f4d8e3ac7a1.png">

Am I missing something ? Could you please provide some pointers.

**Comment by Aleksandr-Filichkin** [comment]
please run 
kubectl create -f taskmanager-deployment.yaml

**Comment by akshatashan** [comment]
Thank you for your reply.

I am already running the taskmanager. I can see the deployment and pod on the minikube dashboard.Attaching screenshot of  the dashboard and the taskmanager log for your reference.

![screenshot 2018-12-05 at 17 16 49](https://user-images.githubusercontent.com/675315/49527279-de766100-f8b1-11e8-9b93-9f6acc2535d2.png)

[logs-from-taskmanager-in-flink-taskmanager-59457f798c-6p4p2.txt](https://github.com/Aleksandr-Filichkin/flink-k8s/files/2649591/logs-from-taskmanager-in-flink-taskmanager-59457f798c-6p4p2.txt)

**Comment by akshatashan** [comment]
@Aleksandr-Filichkin 
The above issue is being referenced in 
This issue is referenced in http://apache-flink-user-mailing-list-archive.2336050.n4.nabble.com/Flink-1-5-4-issues-w-TaskManager-connecting-to-ResourceManager-td23298.html

I was able to resolve it by changing line no 54 in docker_entrypoint_custom.sh to (removed the word cluster

`exec $(drop_privs_cmd) flink "$FLINK_HOME/bin/jobmanager.sh" start-foreground`
Now I see the taskmanagers in the flink ui.
<img width="1119" alt="screenshot 2018-12-05 at 22 11 09" src="https://user-images.githubusercontent.com/675315/49544325-d67ee700-f8da-11e8-8350-8f5f49b659a7.png">
Now, the exception is 
`java.util.concurrent.TimeoutException: Heartbeat of TaskManager with id 2df7ea5fb4c5b039acfa6f597076a786 timed out.`
